### ISSUE TITLE
win7 64位电脑安装atx时出现 ImportError: No module named _markerlib 错误。

### ISSUE THREAD

**Issue by 954324919** [NetEaseGame/AutomatorX#102]
使用命令pip install --upgrade --pre atx安装的时候出现如题的错误。
Requirement already up-to-date: backports.ssl-match-hostname in c:\python27\lib\site-packages (from tornado==4.3->atx)
Collecting distribute (from atx-androguard==3.0->atx)
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\distribute.egg-info
    writing requirements to pip-egg-info\distribute.egg-info\requires.txt
    writing pip-egg-info\distribute.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\distribute.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\distribute.egg-info\dependency_links.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\pip-build-eqpmia\distribute\setup.py", line 58, in <module>
        setuptools.setup(**setup_params)
      File "c:\python27\lib\distutils\core.py", line 152, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "setuptools\command\egg_info.py", line 177, in run
        writer = ep.load(installer=installer)
      File "pkg_resources.py", line 2241, in load
        if require: self.require(env, installer)
      File "pkg_resources.py", line 2254, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "pkg_resources.py", line 2471, in requires
        dm = self._dep_map
      File "pkg_resources.py", line 2682, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "pkg_resources.py", line 2699, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named _markerlib

**Comment by 954324919** [comment]
重新更新pip、setuptools 、distribute就可以了，easy_install distribute或者pip install --upgrade distribute。
