### ISSUE TITLE
pip install --upgrade --pre atx 安装出错

### ISSUE THREAD

**Issue by magaofei** [NetEaseGame/AutomatorX#107]
执行
```shell
sudo pip install --upgrade --pre atx
```
```shell
Installing collected packages: PyYAML, requests, six, facebook-wda, singledispatch, certifi, backports-abc, tornado, maproxy, futures, atx-uiautomator, olefile, Pillow, subprocess32, tqdm, aircv, numpy, imageio, pyparsing, packaging, appdirs, setuptools, distribute, atx-androguard, colorama, atx
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/_yaml.so'

```

改为 
```shell
sudo pip install --ignore-installed --upgrade --pre atx
```
解决了
[参考链接](https://github.com/pypa/pip/issues/3165)

>

**Comment by codeskyblue** [comment]
用brew就不会有权限问题了

**Comment by magaofei** [comment]
用brew 安装 atx ？ 可以吗？搜索不到

**Comment by codeskyblue** [comment]
brew安装python，然后再安装atx

**Comment by magaofei** [comment]
原理和我使用`sudo`修饰不同吗，我使用`sudo`的话应该没有权限问题了吧？

**Comment by codeskyblue** [comment]
sudo也不是万能的，反正你能搞定了就好
