### ISSUE TITLE
小米M2 4.1.1系统报错，5.0系统正常

### ISSUE THREAD

**Issue by HNTSI** [NetEaseGame/AutomatorX#110]
H:\py_venv\study\Scripts\python.exe H:/PyWorkSpace/py_study/atx/atx_demo.py
Traceback (most recent call last):
  File "H:/PyWorkSpace/py_study/atx/atx_demo.py", line 6, in <module>
    d.screenshot('screen.png') # 截图
  File "H:\py_venv\study\lib\site-packages\atx\drivers\mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "H:\py_venv\study\lib\site-packages\atx\drivers\mixin.py", line 387, in screenshot
    screen = self._take_screenshot()
  File "H:\py_venv\study\lib\site-packages\atx\drivers\android.py", line 279, in _take_screenshot
    screen = self._screenshot_minicap()
  File "H:\py_venv\study\lib\site-packages\atx\drivers\android.py", line 231, in _screenshot_minicap
    self._minicap_params(), phone_tmp_file)
  File "H:\py_venv\study\lib\site-packages\atx\drivers\android.py", line 215, in _minicap_params
    rotation = self.rotation 
  File "H:\py_venv\study\lib\site-packages\uiautomator\__init__.py", line 583, in __getattr__
    raise AttributeError("%s attribute not found!" % attr)
AttributeError: rotation attribute not found!

Process finished with exit code 1

**Comment by codeskyblue** [comment]
貌似有多个uiautomator，你需要先将原来的uiautomator卸载掉。可以试试 `pip uninstall uiautomator` 然后重现安装uiautomator
`pip install -U --pre atx-uiautomator`

**Comment by codeskyblue** [comment]
暂时关闭掉了，如果还有问题，在重新open
