### ISSUE TITLE
win10 64bit下Python3.6下安装ATX出错

### ISSUE THREAD

**Issue by mexth** [NetEaseGame/AutomatorX#112]
日志如下：
```
Collecting requests>=2.9.1 (from atx)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting distribute (from atx-androguard==3.0->atx)
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\****\AppData\Local\Temp\pip-build-3eutnrat\distribute\setuptools\__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "C:\Users\****\AppData\Local\Temp\pip-build-3eutnrat\distribute\setuptools\extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "C:\Users\****\AppData\Local\Temp\pip-build-3eutnrat\distribute\setuptools\dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "C:\Users\****\AppData\Local\Temp\pip-build-3eutnrat\distribute\setuptools\command\__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "C:\Users\****\AppData\Local\Temp\pip-build-3eutnrat\distribute\setuptools\command\install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "C:\Users\****\AppData\Local\Temp\pip-build-3eutnrat\distribute\pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\****\AppData\Local\Temp\pip-build-3eutnrat\distribute\
```

期待解决，最近的版本我看支持PY3了，就用3.6的版本试了下，发现还是会出错。

**Comment by codeskyblue** [comment]
可能是 pip 版本太旧的问题。试着这样解决下

```
pip install -U pip wheel
pip install -U distribute
```

**Comment by codeskyblue** [comment]
BTW: I tested with python 3.5

**Comment by mexth** [comment]
跟python的版本3.6有关系看起来，3.6及3.6.1下执行pip install -U distribute 都会出错，所以安装ATX也会出错，log信息都一样的，使用python3.5.3就可以正常安装，也没出错。

**Comment by mexth** [comment]
python3.5下安装成功了，不过目前webide和 weditor这些编辑工具都不能工作。atx-webide运行就会报错，
log是下面这个
Traceback (most recent call last):
  File "C:\Python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python3\lib\site-packages\atxweb\__main__.py", line 6, in <module>
    from atxweb import server
  File "C:\Python3\lib\site-packages\atxweb\server.py", line 32
    print "AutomatorX not installed! Please run `pip install --upgrade atx`"
                                                                           ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by codeskyblue** [comment]
weditor不可以吗？

**Comment by mexth** [comment]
python3.5.3 下weditor连接设备时会报错，下面是日志（2.7下没问题）：
listen port 17310
[W 170401 09:00:31 web:1971] 404 GET /api/v1/contents/main.py (::1) 1.50ms
[I 170401 09:00:31 web:1971] 200 GET /api/v1/version (::1) 1.00ms
SN default
C:\Python3\lib\site-packages\uiautomator\__init__.py:378: ResourceWarning: unclosed file <_io.BufferedWriter name=3>
  self.adb.cmd("push", filename, "/data/local/tmp/").wait()
C:\Python3\lib\site-packages\uiautomator\__init__.py:378: ResourceWarning: unclosed file <_io.BufferedReader name=4>
  self.adb.cmd("push", filename, "/data/local/tmp/").wait()
C:\Python3\lib\site-packages\uiautomator\adb.py:117: ResourceWarning: unclosed file <_io.BufferedWriter name=5>
  return self.cmd("forward", "tcp:%d" % local_port, "tcp:%d" % device_port).wait()
C:\Python3\lib\site-packages\uiautomator\adb.py:117: ResourceWarning: unclosed file <_io.BufferedReader name=6>
  return self.cmd("forward", "tcp:%d" % local_port, "tcp:%d" % device_port).wait()
C:\Python3\lib\site-packages\uiautomator\__init__.py:648: ResourceWarning: unclosed file <_io.BufferedWriter name=7>
  self.server.adb.cmd("shell", "rm", device_file).wait()
C:\Python3\lib\site-packages\uiautomator\__init__.py:648: ResourceWarning: unclosed file <_io.BufferedReader name=8>
  self.server.adb.cmd("shell", "rm", device_file).wait()
C:\Python3\lib\site-packages\atx\drivers\android.py:249: ResourceWarning: unclosed file <_io.BufferedWriter name=5>
  UiaDevice.screenshot(self, tmp_file)
C:\Python3\lib\site-packages\atx\drivers\android.py:249: ResourceWarning: unclosed file <_io.BufferedReader name=6>
  UiaDevice.screenshot(self, tmp_file)
[E 170401 09:00:41 web:1548] Uncaught exception GET /api/v1/devices/default/screenshot (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v1/devices/default/screenshot', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://atx.open.netease.com/', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'Host': 'localhost:17310', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko Core/1.53.2372.400 QQBrowser/9.5.10548.400', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'Accept-Language': 'zh-CN', 'Origin': 'http://atx.open.netease.com'})
    Traceback (most recent call last):
      File "C:\Python3\lib\site-packages\tornado\web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Python3\lib\site-packages\weditor\__main__.py", line 120, in get
        "data": b64data,
      File "C:\Python3\lib\site-packages\tornado\web.py", line 710, in write
        chunk = escape.json_encode(chunk)
      File "C:\Python3\lib\site-packages\tornado\escape.py", line 82, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "C:\Python3\lib\json\__init__.py", line 230, in dumps
        return _default_encoder.encode(obj)
      File "C:\Python3\lib\json\encoder.py", line 198, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "C:\Python3\lib\json\encoder.py", line 256, in iterencode
        return _iterencode(o, 0)
      File "C:\Python3\lib\json\encoder.py", line 179, in default
        raise TypeError(repr(o) + " is not JSON serializable")

**Comment by mexth** [comment]
另外使用html report的时候也会出错。
# coding: utf-8
import atx,time,sys,os
from atx.ext.report import Report

d = atx.connect()
rp = Report(d, save_dir='report')
rp.patch_uiautomator()
。。。测试脚本
if __name__ == '__main__':
    rp.info("Test started", screenshot=d.screenshot())
    测试过程脚本
   rp.close()

在2.7上是OK的，可以正常执行并生成日志，截图。在3.5.3上执行就会出错，log如下
====================== RESTART: D:\python\MXplayer\1.py ======================

Warning (from warnings module):
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 648
    self.server.adb.cmd("shell", "rm", device_file).wait()
ResourceWarning: unclosed file <_io.BufferedReader name=6>

Warning (from warnings module):
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 648
    self.server.adb.cmd("shell", "rm", device_file).wait()
ResourceWarning: unclosed file <_io.BufferedWriter name=5>

Warning (from warnings module):
  File "C:\Python3\lib\site-packages\atx\drivers\android.py", line 249
    UiaDevice.screenshot(self, tmp_file)
ResourceWarning: unclosed file <_io.BufferedReader name=4>

Warning (from warnings module):
  File "C:\Python3\lib\site-packages\atx\drivers\android.py", line 249
    UiaDevice.screenshot(self, tmp_file)
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Traceback (most recent call last):
  File "D:\python\MXplayer\1.py", line 70, in <module>
    MX_list()
  File "D:\python\MXplayer\1.py", line 30, in MX_list
    d(description="更多选项").click()
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 108, in __call__
    return self.func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 81, in _inner
    hook_func(dict(name=fn.__name__, self=instance, args=args, kwargs=kwargs, is_before=False, retval=ret))
  File "C:\Python3\lib\site-packages\atx\ext\report\__init__.py", line 83, in _uia_listener
    cv_last_img = imutils.mark_point(cv_last_img, x, y)
  File "C:\Python3\lib\site-packages\atx\imutils.py", line 150, in mark_point
    cv2.circle(overlay, (x, y), radius, (0, 0, 255), -1)
TypeError: integer argument expected, got float

**Comment by mexth** [comment]
python -m atx gui工具在3.X版本里面使用好像也不正常。
不知道是不是我这边环境的问题。
Traceback (most recent call last):
  File "C:\Python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python3\lib\site-packages\atx\__main__.py", line 167, in <module>
    main()
  File "C:\Python3\lib\site-packages\atx\__main__.py", line 164, in main
    args.func(args)
  File "C:\Python3\lib\site-packages\atx\__main__.py", line 45, in _inner
    __import__(module_path)
  File "C:\Python3\lib\site-packages\atx\cmds\tkgui.py", line 20, in <module>
    import Tkinter as tk
ImportError: No module named 'Tkinter'

**Comment by codeskyblue** [comment]
目前不支持py3的功能

- [ ] `python -matx gui`  这个没计划支持
- [ ] `python -mweditor` 这个是计划支持的
- [ ] `python -matxweb` 这个虽然也计划支持，但是估计没有上一个快

**Comment by mexth** [comment]
好的，等待更新支持，Weditor的工具实用性最高。其他俩工具倒是用的也不多，就是顺手试了下。
另外不知道html report在py3上支持否，目前看使用起来是有问题的，这个还挺有用的，能适配的话最好了，非常感谢。

**Comment by codeskyblue** [comment]
我下周会看下，应该很好支持的。只是语法兼容的问题。或者你也可以提个pr，修复了它

**Comment by codeskyblue** [comment]
参考 <http://docs.opencv.org/3.0-beta/modules/imgproc/doc/drawing_functions.html#circle>

**Comment by mexth** [comment]
水平还是处于起步阶段，目前只会简单的语法来使用现成的框架写脚本。Python也还在学习中，这个还得麻烦作者了。

**Comment by codeskyblue** [comment]
问题迁移到 <https://github.com/NetEaseGame/AutomatorX/issues/114>
