### ISSUE TITLE
html report兼容python3问题

### ISSUE THREAD

**Issue by codeskyblue** [NetEaseGame/AutomatorX#114]
另外使用html report的时候也会出错。
```python
# coding: utf-8
import atx,time,sys,os
from atx.ext.report import Report

d = atx.connect()
rp = Report(d, save_dir='report')
rp.patch_uiautomator()
。。。测试脚本
if __name__ == '__main__':
    rp.info("Test started", screenshot=d.screenshot())
    测试过程脚本
   rp.close()
```

在2.7上是OK的，可以正常执行并生成日志，截图。在3.5.3上执行就会出错，log如下
====================== RESTART: D:\python\MXplayer\1.py ======================

```
Warning (from warnings module):
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 648
    self.server.adb.cmd("shell", "rm", device_file).wait()
ResourceWarning: unclosed file <_io.BufferedReader name=6>

Warning (from warnings module):
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 648
    self.server.adb.cmd("shell", "rm", device_file).wait()
ResourceWarning: unclosed file <_io.BufferedWriter name=5>

Warning (from warnings module):
  File "C:\Python3\lib\site-packages\atx\drivers\android.py", line 249
    UiaDevice.screenshot(self, tmp_file)
ResourceWarning: unclosed file <_io.BufferedReader name=4>

Warning (from warnings module):
  File "C:\Python3\lib\site-packages\atx\drivers\android.py", line 249
    UiaDevice.screenshot(self, tmp_file)
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Traceback (most recent call last):
  File "D:\python\MXplayer\1.py", line 70, in <module>
    MX_list()
  File "D:\python\MXplayer\1.py", line 30, in MX_list
    d(description="更多选项").click()
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 108, in __call__
    return self.func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 81, in _inner
    hook_func(dict(name=fn.__name__, self=instance, args=args, kwargs=kwargs, is_before=False, retval=ret))
  File "C:\Python3\lib\site-packages\atx\ext\report\__init__.py", line 83, in _uia_listener
    cv_last_img = imutils.mark_point(cv_last_img, x, y)
  File "C:\Python3\lib\site-packages\atx\imutils.py", line 150, in mark_point
    cv2.circle(overlay, (x, y), radius, (0, 0, 255), -1)
TypeError: integer argument expected, got float
```

**Comment by codeskyblue** [comment]
参考 http://docs.opencv.org/3.0-beta/modules/imgproc/doc/drawing_functions.html#circle

**Comment by codeskyblue** [comment]
fixed

**Comment by mexth** [comment]
====================== RESTART: D:\python\MXplayer\1.py ======================

Warning (from warnings module):
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 648
    self.server.adb.cmd("shell", "rm", device_file).wait()
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Warning (from warnings module):
  File "C:\Python3\lib\site-packages\atx\drivers\android.py", line 249
    UiaDevice.screenshot(self, tmp_file)
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Traceback (most recent call last):
  File "D:\python\MXplayer\1.py", line 70, in <module>
    MX_list()
  File "D:\python\MXplayer\1.py", line 30, in MX_list
    d(description="更多选项").click()
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 108, in __call__
    return self.func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 81, in _inner
    hook_func(dict(name=fn.__name__, self=instance, args=args, kwargs=kwargs, is_before=False, retval=ret))
  File "C:\Python3\lib\site-packages\atx\ext\report\__init__.py", line 83, in _uia_listener
    cv_last_img = imutils.mark_point(cv_last_img, x, y)
  File "C:\Python3\lib\site-packages\atx\imutils.py", line 154, in mark_point
    cv2.circle(overlay, center, radius, color, -1)
TypeError: integer argument expected, got float
>>> 

python 3.5下面各个组件版本都更新到最新之后，html report使用起来还是有问题。

**Comment by mexth** [comment]
已经完美解决，感谢作者的更新，好几个版本。

**Comment by codeskyblue** [comment]
可以testerhome.com发篇文章分享下使用体验
