### ISSUE TITLE
使用多设备执行脚本的时候，html report功能无法正常使用

### ISSUE THREAD

**Issue by mexth** [NetEaseGame/AutomatorX#120]
两台手机，同时执行脚本，不使用html report功能可以正常完成脚本，一旦使用该功能执行就会出问题
脚本结构如下：
```
# coding: utf-8
import atx,time,sys,os,traceback,multiprocessing
from atx.ext.report import Report

def RunTest(serials):
    from multiprocessing.dummy import Pool as ThreadPool
    pool = ThreadPool()
    pool.map(SingleTest, serials)
    pool.close()
    pool.join()

def SingleTest(serialno):
    d = atx.connect(serialno)
    rp = Report(d, save_dir=serialno)
    rp.patch_uiautomator()
    rp.info("Test started", screenshot=d.screenshot())
    d.start_app( "com.mxtech.videoplayer.pro","com.mxtech.videoplayer.pro.ActivityMediaList")
#    rp.assert_ui_exists(d(description='更多选项'), desc='Hello UI')
    d(description="更多选项").click()
    ...主体脚本...
if __name__ == '__main__':
    RunTest(["5406a354","CB5A21SX9A"])
```

出错的log：
```
>>> 
========================== RESTART: D:\python\11.py ==========================
2017-04-13 08:34:00.474 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
2017-04-13 08:34:16.530 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again

Traceback (most recent call last):
  File "D:\python\11.py", line 55, in <module>
    RunTest(["5406a354","CB5A21SX9A"])
  File "D:\python\11.py", line 9, in RunTest
    pool.map(SingleTest, serials)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
IOError: unrecognized data stream contents when reading image file
2017-04-13 08:34:17.151 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
>>> Next
Back to view list
list test end 
```

**Comment by codeskyblue** [comment]
一台手机单独执行也会报错吗？

**Comment by mexth** [comment]
单台设备不会报错，可以正常使用的。

**Comment by codeskyblue** [comment]
@mexth 出错的时候你查看下`adb forward --list`的输出。

>可能的修复方法备忘：
Note: need to implement a new method `forward_to_freeport(serial, device_port)`
with command `adb forward --no-rebind`

**Comment by codeskyblue** [comment]
@mexth should be fixed, you can update atx and retry again

**Comment by mexth** [comment]
更新到最新版本后：
启用html report后多设备运行还是会有问题
Python2 环境下的log（运行3次好像每次显示的错误都不完全一样）：
```
Traceback (most recent call last):
  File "D:\python\11.py", line 55, in <module>
    RunTest(["5406a354","CB5A21SX9A"])
  File "D:\python\11.py", line 9, in RunTest
    pool.map(SingleTest, serials)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
SyntaxError: broken PNG file (chunk '\x1b\x00\xf0\xd9')
>>> 

Traceback (most recent call last):
  File "D:\python\11.py", line 55, in <module>
    RunTest(["5406a354","CB5A21SX9A"])
  File "D:\python\11.py", line 9, in RunTest
    pool.map(SingleTest, serials)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
IOError: unrecognized data stream contents when reading image file
>>> 
========================== RESTART: D:\python\11.py ==========================
2017-04-14 14:29:11.931 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again

Traceback (most recent call last):
  File "D:\python\11.py", line 55, in <module>
    RunTest(["5406a354","CB5A21SX9A"])
  File "D:\python\11.py", line 9, in RunTest
    pool.map(SingleTest, serials)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
IOError: image file is truncated
>>> 2017-04-14 14:29:14.148 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
```

python3 环境下的log
```
========================== RESTART: D:\python\11.py ==========================
2017-04-14 14:13:21.006 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
Traceback (most recent call last):
  File "D:\python\11.py", line 55, in <module>
    RunTest(["5406a354","CB5A21SX9A"])
  File "D:\python\11.py", line 9, in RunTest
    pool.map(SingleTest, serials)
  File "C:\Python3\lib\multiprocessing\pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Python3\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
  File "C:\Python3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\python\11.py", line 24, in SingleTest
    d(description="更多选项").click()
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 108, in __call__
    return self.func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 81, in _inner
    hook_func(dict(name=fn.__name__, self=instance, args=args, kwargs=kwargs, is_before=False, retval=ret))
  File "C:\Python3\lib\site-packages\atx\ext\report\__init__.py", line 88, in _uia_listener
    screen_after = self._save_screenshot(append_gif=True)
  File "C:\Python3\lib\site-packages\atx\ext\report\__init__.py", line 207, in _save_screenshot
    screen.save(relpath)
  File "C:\Python3\lib\site-packages\PIL\Image.py", line 1793, in save
    self.load()
  File "C:\Python3\lib\site-packages\PIL\ImageFile.py", line 212, in load
    s = read(self.decodermaxblock)
  File "C:\Python3\lib\site-packages\PIL\PngImagePlugin.py", line 591, in load_read
    cid, pos, length = self.png.read()
  File "C:\Python3\lib\site-packages\PIL\PngImagePlugin.py", line 116, in read
    raise SyntaxError("broken PNG file (chunk %s)" % repr(cid))
  File "<string>", line None
SyntaxError: broken PNG file (chunk b'\x00\x00\x00\x00')
>>> 2017-04-14 14:13:23.284 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
```
python3 环境下log2：

```
>>> 
========================== RESTART: D:\python\11.py ==========================
2017-04-14 14:41:55.264 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
2017-04-14 14:41:57.029 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\PIL\ImageFile.py", line 212, in load
    s = read(self.decodermaxblock)
  File "C:\Python3\lib\site-packages\PIL\PngImagePlugin.py", line 591, in load_read
    cid, pos, length = self.png.read()
  File "C:\Python3\lib\site-packages\PIL\PngImagePlugin.py", line 113, in read
    length = i32(s)
  File "C:\Python3\lib\site-packages\PIL\_binary.py", line 74, in i32be
    return unpack(">I", c[o:o+4])[0]
struct.error: unpack requires a bytes object of length 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\11.py", line 55, in <module>
    RunTest(["5406a354","CB5A21SX9A"])
  File "D:\python\11.py", line 9, in RunTest
    pool.map(SingleTest, serials)
  File "C:\Python3\lib\multiprocessing\pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Python3\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
  File "C:\Python3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\python\11.py", line 24, in SingleTest
    d(description="更多选项").click()
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 108, in __call__
    return self.func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\uiautomator\__init__.py", line 81, in _inner
    hook_func(dict(name=fn.__name__, self=instance, args=args, kwargs=kwargs, is_before=False, retval=ret))
  File "C:\Python3\lib\site-packages\atx\ext\report\__init__.py", line 88, in _uia_listener
    screen_after = self._save_screenshot(append_gif=True)
  File "C:\Python3\lib\site-packages\atx\ext\report\__init__.py", line 207, in _save_screenshot
    screen.save(relpath)
  File "C:\Python3\lib\site-packages\PIL\Image.py", line 1793, in save
    self.load()
  File "C:\Python3\lib\site-packages\PIL\ImageFile.py", line 217, in load
    raise IOError("image file is truncated")
OSError: image file is truncated
```

**Comment by codeskyblue** [comment]
Insteresting. 提供下两个手机的型号吧。以及是否安装了minicap, 执行错误时候的 `adb forward --list` 输出

**Comment by codeskyblue** [comment]
另外检查下你的C盘是不是没有空间了

**Comment by mexth** [comment]
手机型号 一个是sony z3 安卓6.0，一个是小米3 安卓4.4. 分别跑脚本的时候都OK，一起跑就会出问题。
C盘空间很充足还有74G，minicap未安装。插件里面就open cv，weditor和webide

**Comment by codeskyblue** [comment]
adb版本和 adb forward --list的输出呢

**Comment by mexth** [comment]
5406a354 tcp:9009 tcp:9008
CB5A21SX9A tcp:9010 tcp:9008

 这是adb forward --list的输出

**Comment by codeskyblue** [comment]
你可是试试在linux机器上是否还错误，还有一个办法是使用subprocess来代替multiprocessing

**Comment by mexth** [comment]
在ubuntu17.04上试了下，可以跑完，并生产相应html report。  不过两台设备是依次执行的，执行完一台后，另一台才开始执行一样的操作，而不是同时在两台设备上执行操作。
另外验证了下，不使用html report也是一样的情况。

**Comment by mexth** [comment]
subprocess之前没用过，还在学习怎么用起来。

**Comment by mexth** [comment]
更新反馈，ubuntu里面，设定好processes数量后，html report一样不能使用了。使用就会报错，和windows下面的log一样。
