### ISSUE TITLE
.info方法 HTTPConnectionPool(host='127.0.0.1', port=9009): Read timed out

### ISSUE THREAD

**Issue by godzx001** [NetEaseGame/AutomatorX#70]
## What steps will reproduce the problem?
有些方法会 HTTPConnectionPool(host='127.0.0.1', port=9009): Read timed out

例如： d(className="android.widget.EditText", index=0).info

## What is the expected output?
.info 返回控件属性

## What do you see instead?
HTTPConnectionPool(host='127.0.0.1', port=9009): Read timed out
## Do you have any log or screenshots?

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 880, in info
    return self.jsonrpc.objInfo(self.selector)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 409, in wrapper
    return _JsonRPCMethod(url, method, timeout, False)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 404, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 196, in __call__
    return self.remote_call(data)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 177, in remote_call
    data=json.dumps(data).encode('utf-8'))
  File "C:\Python27\lib\site-packages\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=9009): Read timed out. (read timeout=60)

Android Debug Bridge version 1.0.36
Revision e02fe72a18c3-android

**Comment by codeskyblue** [comment]
先放着，还没想好怎么处理

**Comment by godzx001** [comment]
1.0.15.dev1
版本貌似可以用。。。

**Comment by codeskyblue** [comment]
难道自动就好了，记得中间调整过超时时间
