### ISSUE TITLE
mac 下pip安装失败

### ISSUE THREAD

**Issue by muxiaFrank** [NetEaseGame/AutomatorX#75]
用pip安装 atx老是报错 这个问题怎么解决的（搜了半天也没找到原因）
加了权限依然报错如下
```
 DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-IiDFF_-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'

```

**Comment by wuxc** [comment]
Mac的System Integrity Protection (SIP)系统完整性保护，可以暂时关闭一下

http://www.macx.cn/forum.php?mod=viewthread&tid=2173082&highlight=rootless

**Comment by muxiaFrank** [comment]
@wuxc  关了之后 又抛出个错误
```OSError: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/setuptools-17.1.1-py2.7.egg'```
import atx 虽然不是出现无这个包的错误，但是还是有错误
```>>> import atx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/atx/__init__.py", line 21, in <module>
    from atx.drivers import Pattern, Bounds, ImageCrop
  File "/Library/Python/2.7/site-packages/atx/drivers/__init__.py", line 8, in <module>```
第一次用mac 问的问题较为没水平 见谅

**Comment by wuxc** [comment]
试下 pip install -U setuptools

**Comment by muxiaFrank** [comment]
@wuxc  还是不行 回头再说吧 比我搭个appium的都麻烦

**Comment by codeskyblue** [comment]
不要用系统自带的python 用brew安装的
